export const features = [
  {
    id: 'ethnicity',
    name: 'DNA Ethnicity Analysis',
    description: 'AI-powered analysis of your ethnic composition from DNA data',
    icon: '🌍',
    color: '#3B82F6',
    apiPath: '/ethnicity',
    columns: ['region', 'sub_region', 'percentage', 'confidence', 'population_reference'],
    displayColumns: ['Region', 'Sub Region', 'Percentage', 'Confidence', 'Reference Panel'],
    formFields: [
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'sub_region', label: 'Sub Region', type: 'text', required: true },
      { key: 'percentage', label: 'Percentage', type: 'number', required: true },
      { key: 'confidence', label: 'Confidence', type: 'select', options: ['High', 'Medium', 'Low'], required: true },
      { key: 'population_reference', label: 'Reference Panel', type: 'text' },
    ],
  },
  {
    id: 'ancestors',
    name: 'Ancestor Discovery',
    description: 'AI helps discover and research your ancestors with historical context',
    icon: '👴',
    color: '#8B5CF6',
    apiPath: '/ancestors',
    columns: ['name', 'birth_year', 'death_year', 'birth_place', 'occupation', 'relationship'],
    displayColumns: ['Name', 'Birth Year', 'Death Year', 'Birth Place', 'Occupation', 'Relationship'],
    formFields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'birth_year', label: 'Birth Year', type: 'number' },
      { key: 'death_year', label: 'Death Year', type: 'number' },
      { key: 'birth_place', label: 'Birth Place', type: 'text' },
      { key: 'death_place', label: 'Death Place', type: 'text' },
      { key: 'occupation', label: 'Occupation', type: 'text' },
      { key: 'relationship', label: 'Relationship', type: 'text', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'health-risks',
    name: 'Health Predisposition',
    description: 'AI analyzes genetic health risk factors and provides insights',
    icon: '🏥',
    color: '#EF4444',
    apiPath: '/health-risks',
    columns: ['condition', 'gene', 'variant', 'risk_level', 'risk_percentage', 'category'],
    displayColumns: ['Condition', 'Gene', 'Variant', 'Risk Level', 'Risk %', 'Category'],
    formFields: [
      { key: 'condition', label: 'Condition', type: 'text', required: true },
      { key: 'gene', label: 'Gene', type: 'text', required: true },
      { key: 'variant', label: 'Variant', type: 'text', required: true },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['High', 'Moderate', 'Low'], required: true },
      { key: 'risk_percentage', label: 'Risk Percentage', type: 'number' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'migration',
    name: 'Migration Patterns',
    description: 'AI traces and analyzes ancestral migration routes through history',
    icon: '🗺️',
    color: '#10B981',
    apiPath: '/migration',
    columns: ['origin', 'destination', 'era', 'year_range', 'reason'],
    displayColumns: ['Origin', 'Destination', 'Era', 'Year Range', 'Reason'],
    formFields: [
      { key: 'origin', label: 'Origin', type: 'text', required: true },
      { key: 'destination', label: 'Destination', type: 'text', required: true },
      { key: 'era', label: 'Era', type: 'text', required: true },
      { key: 'year_range', label: 'Year Range', type: 'text' },
      { key: 'reason', label: 'Reason', type: 'text' },
      { key: 'route', label: 'Route', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'relationships',
    name: 'Family Relationships',
    description: 'AI determines and explains family relationships from DNA data',
    icon: '👨‍👩‍👧‍👦',
    color: '#F59E0B',
    apiPath: '/relationships',
    columns: ['person_name', 'relationship_type', 'shared_cm', 'shared_segments', 'confidence'],
    displayColumns: ['Person', 'Relationship', 'Shared cM', 'Segments', 'Confidence %'],
    formFields: [
      { key: 'person_name', label: 'Person Name', type: 'text', required: true },
      { key: 'relationship_type', label: 'Relationship Type', type: 'text', required: true },
      { key: 'shared_cm', label: 'Shared cM', type: 'number', required: true },
      { key: 'shared_segments', label: 'Shared Segments', type: 'number', required: true },
      { key: 'confidence', label: 'Confidence %', type: 'number' },
      { key: 'match_date', label: 'Match Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  {
    id: 'haplogroups',
    name: 'Haplogroup Analysis',
    description: 'AI explores your ancient lineage through haplogroup deep dive',
    icon: '🧬',
    color: '#6366F1',
    apiPath: '/haplogroups',
    columns: ['haplogroup', 'type', 'origin_region', 'age', 'description'],
    displayColumns: ['Haplogroup', 'Type', 'Origin', 'Age', 'Description'],
    formFields: [
      { key: 'haplogroup', label: 'Haplogroup', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['paternal', 'maternal'], required: true },
      { key: 'origin_region', label: 'Origin Region', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'migration_path', label: 'Migration Path', type: 'textarea' },
    ],
  },
  {
    id: 'traits',
    name: 'Genetic Traits',
    description: 'AI predicts and explains physical and behavioral traits from DNA',
    icon: '👁️',
    color: '#EC4899',
    apiPath: '/traits',
    columns: ['trait_name', 'predicted_outcome', 'gene', 'variant', 'probability', 'category'],
    displayColumns: ['Trait', 'Prediction', 'Gene', 'Variant', 'Probability %', 'Category'],
    formFields: [
      { key: 'trait_name', label: 'Trait Name', type: 'text', required: true },
      { key: 'predicted_outcome', label: 'Predicted Outcome', type: 'text', required: true },
      { key: 'gene', label: 'Gene', type: 'text' },
      { key: 'variant', label: 'Variant', type: 'text' },
      { key: 'probability', label: 'Probability %', type: 'number' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'timelines',
    name: 'Ancestor Timeline',
    description: 'AI creates rich historical timelines of ancestor life events',
    icon: '📜',
    color: '#14B8A6',
    apiPath: '/timelines',
    columns: ['ancestor_name', 'event_type', 'year', 'location', 'description'],
    displayColumns: ['Ancestor', 'Event', 'Year', 'Location', 'Description'],
    formFields: [
      { key: 'ancestor_name', label: 'Ancestor Name', type: 'text', required: true },
      { key: 'event_type', label: 'Event Type', type: 'text', required: true },
      { key: 'year', label: 'Year', type: 'number', required: true },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'source', label: 'Source', type: 'text' },
    ],
  },
  {
    id: 'culture',
    name: 'Cultural Heritage',
    description: 'AI explores cultural traditions and customs of your ancestors',
    icon: '🎭',
    color: '#F97316',
    apiPath: '/culture',
    columns: ['culture_name', 'region', 'tradition', 'time_period', 'category'],
    displayColumns: ['Culture', 'Region', 'Tradition', 'Period', 'Category'],
    formFields: [
      { key: 'culture_name', label: 'Culture Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'tradition', label: 'Tradition', type: 'text', required: true },
      { key: 'time_period', label: 'Time Period', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'surnames',
    name: 'Surname Origins',
    description: 'AI researches the etymology and history of family surnames',
    icon: '📛',
    color: '#84CC16',
    apiPath: '/surnames',
    columns: ['surname', 'origin_language', 'origin_country', 'meaning', 'first_recorded', 'category'],
    displayColumns: ['Surname', 'Language', 'Country', 'Meaning', 'First Recorded', 'Category'],
    formFields: [
      { key: 'surname', label: 'Surname', type: 'text', required: true },
      { key: 'origin_language', label: 'Origin Language', type: 'text', required: true },
      { key: 'origin_country', label: 'Origin Country', type: 'text', required: true },
      { key: 'meaning', label: 'Meaning', type: 'text' },
      { key: 'first_recorded', label: 'First Recorded', type: 'text' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'dna-matches',
    name: 'DNA Match Analysis',
    description: 'AI analyzes and interprets DNA match significance',
    icon: '🔬',
    color: '#06B6D4',
    apiPath: '/dna-matches',
    columns: ['match_name', 'shared_cm', 'shared_segments', 'predicted_relationship', 'confidence'],
    displayColumns: ['Match Name', 'Shared cM', 'Segments', 'Predicted Relationship', 'Confidence %'],
    formFields: [
      { key: 'match_name', label: 'Match Name', type: 'text', required: true },
      { key: 'shared_cm', label: 'Shared cM', type: 'number', required: true },
      { key: 'shared_segments', label: 'Shared Segments', type: 'number', required: true },
      { key: 'chromosomes', label: 'Chromosomes', type: 'text' },
      { key: 'predicted_relationship', label: 'Predicted Relationship', type: 'text' },
      { key: 'confidence', label: 'Confidence %', type: 'number' },
      { key: 'match_date', label: 'Match Date', type: 'date' },
    ],
  },
  {
    id: 'documents',
    name: 'Document Analysis',
    description: 'AI analyzes and interprets genealogical documents',
    icon: '📄',
    color: '#78716C',
    apiPath: '/documents',
    columns: ['document_type', 'title', 'document_date', 'person_name', 'location'],
    displayColumns: ['Type', 'Title', 'Date', 'Person', 'Location'],
    formFields: [
      { key: 'document_type', label: 'Document Type', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'document_date', label: 'Document Date', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'person_name', label: 'Person Name', type: 'text' },
      { key: 'content_summary', label: 'Content Summary', type: 'textarea' },
      { key: 'source', label: 'Source', type: 'text' },
    ],
  },
  {
    id: 'recipes',
    name: 'Heritage Recipes',
    description: 'AI discovers traditional recipes connected to your ancestral regions',
    icon: '🍲',
    color: '#DC2626',
    apiPath: '/recipes',
    columns: ['recipe_name', 'origin_region', 'origin_country', 'cuisine_type', 'era'],
    displayColumns: ['Recipe', 'Region', 'Country', 'Type', 'Era'],
    formFields: [
      { key: 'recipe_name', label: 'Recipe Name', type: 'text', required: true },
      { key: 'origin_region', label: 'Origin Region', type: 'text', required: true },
      { key: 'origin_country', label: 'Origin Country', type: 'text', required: true },
      { key: 'cuisine_type', label: 'Cuisine Type', type: 'text' },
      { key: 'era', label: 'Era', type: 'text' },
      { key: 'key_ingredients', label: 'Key Ingredients', type: 'textarea' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    id: 'reports',
    name: 'Heritage Reports',
    description: 'AI generates comprehensive genealogy and heritage reports',
    icon: '📊',
    color: '#7C3AED',
    apiPath: '/reports',
    columns: ['report_type', 'subject_name', 'regions', 'time_span', 'status'],
    displayColumns: ['Type', 'Subject', 'Regions', 'Time Span', 'Status'],
    formFields: [
      { key: 'report_type', label: 'Report Type', type: 'text', required: true },
      { key: 'subject_name', label: 'Subject Name', type: 'text', required: true },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'key_findings', label: 'Key Findings', type: 'textarea' },
      { key: 'regions', label: 'Regions', type: 'text' },
      { key: 'time_span', label: 'Time Span', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['completed', 'in_progress', 'pending'] },
    ],
  },
  {
    id: 'ancient',
    name: 'Ancient Ancestry',
    description: 'AI explores deep ancient origins and connections to ancient populations',
    icon: '🏛️',
    color: '#A855F7',
    apiPath: '/ancient',
    columns: ['population_name', 'region', 'time_period', 'affinity_percentage', 'archaeological_sites'],
    displayColumns: ['Population', 'Region', 'Time Period', 'Affinity %', 'Archaeological Sites'],
    formFields: [
      { key: 'population_name', label: 'Population Name', type: 'text', required: true },
      { key: 'region', label: 'Region', type: 'text', required: true },
      { key: 'time_period', label: 'Time Period', type: 'text', required: true },
      { key: 'affinity_percentage', label: 'Affinity %', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'archaeological_sites', label: 'Archaeological Sites', type: 'text' },
    ],
  },
];
